spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: book

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.cr.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local