spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: company
      embedded:
        enabled: true
        version: 5.0.14

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
